CREATE TABLE Usuario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(255) NOT NULL,
 Correo_Electronico VARCHAR(255) NOT NULL UNIQUE,
  Contraseña VARCHAR(255) NOT NULL,
  Rol VARCHAR(50) NOT NULL DEFAULT 'user',
  Fecha_Registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
```